- lib/zendesk_api/configuration.rb
- spec/core/configuration_spec.rb
Currently we don't set a default open_timeout, and rely on the default timeouts specified by each client adapter. The default client adapter, Net::HTTP, [has a nil an `open_timeout` value](http://ruby-doc.org/stdlib-2.2.0/libdoc/net/http/rdoc/Net/HTTP.html#open_timeout), which can cause a request to block indefinitely if network traffic is dropped. This can cause a serious issues in background services or workers. I'd expect a small number of our users are manually configuring this value until they run into an issue. It would be helpful to automatically work around issues like #176 by default.
Adapter-wise, `open_timeout` is used by all the Faraday adapters. Here's a run down of the default open_timeout values in the available clients:
- excon: `:connect_timeout      => 60` …
> set a default open_timeout of 10 seconds

- README.md
- lib/zendesk_api/resources.rb
- spec/core/client_spec.rb
@zendesk/mongooses
@ggrossman Since this is public we'll keep the endpoint for a while but we plan to remove it.
There's no documentation in our developer portal for the endpoint and you wouldn't know that you can use this resource unless you dug in the source code. How long do you think that we need to maintain the endpoint?
> Rename CertificationAddress into Address in Voice

- lib/zendesk_api/middleware/response/raise_error.rb
- spec/core/middleware/response/raise_error_spec.rb
Since https://github.com/zendesk/zendesk/pull/15158 was deployed, uploads that exceed a plan's maximum file size fail with `413` instead of `422`. Ideally we'd be able to capture the nice, internationalized errors in these responses like we did when they were still returning `422`s.
Alternatively, we could add a new error class specifically for the new response code. I am not sure which option is preferable here.
/cc @steved, @ggrossman
> Capture error messages in 413 responses

- lib/zendesk_api/collection.rb
When trying to enumerate an incremental_export, the `all!` method will loop continuously until the Zendesk API returns a **429** error. This commit fixes that issue. You can replicate the problem on the current master branch with the following code:
```ruby
ZendeskAPI::User.incremental_export(zdclient, 0).all! {|u|
puts "User: #{u.id}, #{u.name}"
}
```
There is still an issue of infinitely looping when trying to use the `per_page` method that this commit does not address and it does not look like that is as easy of a fix. It might be best just to advise people not to use `per_page` with the `incremental_export` methods since they don't support a **per_page** parameter.
> Fix logic in _all so incremental exports don't infinitely loop

- lib/zendesk_api/actions.rb
- lib/zendesk_api/resource.rb
- spec/core/read_resource_spec.rb
Implements `reload!` on read resources. This is useful for `JobStatus` and possibly other places to.
Most of the diff is just me putting the find methods inside of a ClassMethods module.
/cc @zendesk/octo
- None
> Introduce reload!

- lib/zendesk_api/actions.rb
- spec/core/bulk_actions_spec.rb
- spec/core/collection_spec.rb
destroy_many uses a comma separated list of ids
/cc @zendesk/octo @steved @aghassipour 
- None
> destroy_many uses a comma separated list of ids

- lib/zendesk_api/error.rb
- spec/core/middleware/response/raise_error_spec.rb
I found out that even after https://github.com/zendesk/zendesk_api_client_rb/pull/221 we don't get meaningful error messages for uploads that exceed the maximum size. This is because the structure of an upload's errors hash differs from the typical `RecordInvalid` message. 
This PR adds support for falling back to an error's description if details are missing.
@steved, @ggrossman
> Get RecordInvalid message from description in absence of details

- lib/zendesk_api/resources.rb
`AppNotification` overrides `handle_response` and tries to replace its attributes with the response. `api/v2/apps/notify.json` currently returns an empty string as the response so replacing attributes will raise the following error:
```
NoMethodError: undefined method `each_pair' for " ":String
from /opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/hashie-3.3.1/lib/hashie/mash.rb:177:in `deep_update'
from /opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/zendesk_api-1.4.6/lib/zendesk_api/track_changes.rb:40:in `replace'
from /opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/zendesk_api-1.4.6/lib/zendesk_api/resources.rb:686:in `handle_response'
from /opt/boxen/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/zendesk_api-1.4.6/lib/zendesk_api/actions.rb:43:in `save!'
from …
```
> AppNotification#handle_response: only call @attributes#replace if response is a hash

- lib/zendesk_api/client.rb
- lib/zendesk_api/middleware/response/sanitize_response.rb
- spec/core/middleware/response/sanitize_response_spec.rb
- zendesk_api.gemspec
If a response contains characters with bad UTF-8 characters the ParseIsoDates middleware blows up when doing the Regex. 
This PR is just to allow the client to handle that case.
/cc @henders @steved @grosser
> Handling bad utf-8 characters on a response

- lib/zendesk_api/client.rb
- spec/core/client_spec.rb
Hey,
My team had a production bug caused by calling .empty? on a client object.
the client api doesn't handle question marks well so I added this handling.
Also added test. :)
> fix method_as_class to handle non alphanumeric

- Gemfile
- zendesk_api.gemspec
Clients using Ruby < 2.0 should themselves set a version restriction so they don't install mime-types >= v3.0.
> Remove version constraint on mime-types

- lib/zendesk_api/associations.rb
Ruby 2.4 unifies Fixnum and Bignum into Integer: https://bugs.ruby-lang.org/issues/12005
> Support for unified Integer class in Ruby 2.4+

- Gemfile
- README.md
- lib/zendesk_api/middleware/response/sanitize_response.rb
- spec/core/spec_helper.rb
- zendesk_api.gemspec
For people using Ruby 2.1 or newer, this gem is dead weight. Let's just document that if you use an old version of Ruby, you need to install a gem that implements `scrub!` for you.
> Remove dependency on scrub_rb

- .travis.yml
- lib/zendesk_api/error.rb
- spec/core/middleware/response/raise_error_spec.rb
Currently getting random errors like: `ZendeskAPI::Error::NetworkError: the server responded with status 500
` ... would be much nicer to receive: `ZendeskAPI::Error::NetworkError: the server responded with status 500 -- get https://fail.zendesk.com/api/v2/incremental/tickets.json?include=users%2Cgroups%2Corganizations%2Cmetric_sets%2Cdates&start_time=1425754064`
@bquorning @vgrigoruk
> show what exactly went wrong

- spec/core/collection_spec.rb
Fix failure spec.
`to_proc` is different from RSpec master.
https://github.com/rspec/rspec-expectations/blob/master/lib/rspec/matchers/built_in/yield.rb#L38
> Fix failure spec in master branch

- .travis.yml
Use newest bundler reported in bundler/bundler#3559
Failure job
https://travis-ci.org/zendesk/zendesk_api_client_rb/jobs/273512217
> Use newest bundler in travis CI (Fix travis CI)

- lib/zendesk_api/actions.rb
- spec/core/bulk_actions_spec.rb
Support batch update resources.
e.g. https://developer.zendesk.com/rest_api/docs/core/tickets#batch-updates
> Support batch update resources

- .travis.yml
Travis CI failed to install jruby by using rvm.
This is reported by rvm/rvm#4210.
Specify jruby versions in `.travis.yml` until the problem are resolved.
> Specify jruby versions

- lib/zendesk_api/middleware/response/logger.rb
Zendesk API returns the response status 400 range and the error messages as its body when the request was not successful.
https://developer.zendesk.com/rest_api/docs/core/introduction#400-range
But the response status is only output to the log now.
So, I would like to suggest to log the response body also to understand why the request was failure.
> Log response body on 400 range

- .travis.yml
- README.md
- spec/core/middleware/response/sanitize_response_spec.rb
- zendesk_api.gemspec
Goal: Get Travis-CI builds functional again for this repo.
* Drop Travis-CI runs for Ruby versions < 2.3, which are now EOL
* Add Ruby 2.4, 2.5, and 2.6 to Travis-CI test matrix
* Fix sanitize_response_spec to work for Ruby >= 2.4. Invalid Unicode code points are no longer accepted for `\uXXXX` sequences.
> Update Ruby versions in .travis.yml

- lib/zendesk_api/resources.rb
- spec/core/collection_spec.rb
- spec/live/ticket_spec.rb
The `/exports/tickets` endpoint is no longer supported. Use `/incremental/tickets` instead (see the Zendesk docs on [Incremental Ticket Export](https://developer.zendesk.com/rest_api/docs/support/incremental_export#incremental-ticket-export)).
This is essentially the same change as #287 but also updates the tests. Fixes #243 and #276.
> Update ticket incremental export endpoint

- lib/zendesk_api/actions.rb
- lib/zendesk_api/resources.rb
- spec/core/bulk_actions_spec.rb
- spec/fixtures/test_resources.rb
The API for this is slightly different than the API in `CreateMany` and `UpdateMany` because the endpoint doesn't support the ID-based query parameters.
I did not add a live test because it appears that none of the bulk actions have them.
> Add support to create or update many users and remove unsupported update many users

- lib/zendesk_api/resource.rb
- spec/core/resource_spec.rb
To accompany the existing `method_missing` method
> ZendeskAPI::Resource: Define respond_to_missing?

- README.md
- lib/zendesk_api/client.rb
- lib/zendesk_api/configuration.rb
- lib/zendesk_api/error.rb
- lib/zendesk_api/middleware/request/raise_rate_limited.rb
- spec/core/middleware/request/raise_rate_limited_spec.rb
The motivation of this came from us using Zendesk API as part of background jobs. If we are rate limited, we do not want the job to be hogging the background worker, and instead raise an error and be requeued immediately. This will allow us to handle the error and delay the job for a later time. And also for other jobs to be processed asap.
> Add option to raise error when rate limited

- spec/core/configuration_spec.rb
Broke rubocop (again) when I merged https://github.com/zendesk/zendesk_api_client_rb/pull/335 yesterday. Sorry about that!
> Fix missing space inside literal brances

- Gemfile
Webmock "< 2" . [doesn't play very well with](https://github.com/bblimke/webmock/issues/683) > Ruby 2.4 
Also, reordered a bit the Gemfile to exclude testing deps
> Unpin webmock version and reorder Gemfile

- README.md
The `.png` badges look pretty terrible on high resolution monitors:
How about using `.svg` instead:
> Use SVG badges on readme, instead of PNG

- .travis.yml
Travis doesn't allow pull requests builds to access encrypted secrets for security reasons, so we can't really use them on pull requests created by external contributors, so I've configured travis to no run those tests on PRs builds.
The idea then is to merge a PR to an integration branch (`spec_live`) to ensure the live testing is working before merging. That's why I've added that branch to the lists of branches that triggers builds by default
> Do not run spec lives in forks

- README.md
- lib/zendesk_api/configuration.rb
- spec/core/client_spec.rb
- spec/core/configuration_spec.rb
I noticed there's no timeout after a connection has been established. The network can error in this case. I'm not sure if we have some default on the Faraday side or if something is done under the hood for long running requests so I thought I should open this MR as a consideration for this case.
> Set a request default timeout for zendesk client

- zendesk_api.gemspec
Add [project metadata](https://guides.rubygems.org/specification-reference/#metadata) to the gemspec file. This'll allow people to more easily access the source code, raise issues and read the changelog. These `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, `wiki_uri` and `source_code_uri` links will appear on the rubygems page at https://rubygems.org/gems/zendesk_api after the next release.
> Add project metadata to the gemspec

- lib/zendesk_api/client.rb
- spec/core/client_spec.rb
Fixes: https://github.com/zendesk/zendesk_api_client_rb/issues/373
> Provide a meaningful error when using token auth and username is nil

- lib/zendesk_api/actions.rb
- spec/live/user_spec.rb
The `CreateOrUpdate` is not working properly since it's using the plural name of the resource for the root key, and it should be using the singular name since we are updating an individual resource
Fixes https://github.com/zendesk/zendesk_api_client_rb/issues/308
> Use `singular_resource_name` on CreateOrUpdate actions

- lib/zendesk_api/collection.rb
- lib/zendesk_api/error.rb
- lib/zendesk_api/resources.rb
The Faraday gem introduced a new [error class structure in v0.9.0](https://github.com/lostisland/faraday/blob/v0.9.0/lib/faraday/error.rb). Let's reference this new structure instead of the [backward compatibility enabling alias](https://github.com/lostisland/faraday/blob/v0.9.0/lib/faraday/error.rb#L49-L52).
Since Faraday version 0.17.1 a deprecation warning is printed to `STDERR`. This resolves it.
As this new error structure was introduced in Faraday version 0.9.0 and the `zendesk_api` gem requires version 0.9.0 as a minimum, this is a safe change to make.
https://github.com/zendesk/zendesk_api_client_rb/blob/7fe691d0c34f818c13b1b20d1c921b4701e99e73/zendesk_api.gemspec#L29
Fixes #408.
> Resolve Faraday deprecation notice

- lib/zendesk_api/version.rb
I set out to fix the Faraday deprecations errors that were scattered all over our test outputs, errors like `NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0` - only to find that [someone already had fixed this recently](https://github.com/zendesk/zendesk_api_client_rb/pull/409) 🎉 
Tagging and releasing a new version of the gem, to include these changes.
@orien @nogates @romikoops (tagging recent contributors for review, as I am a stranger to this repo)
@zendesk/guide-test-engineering
> Release new version

- lib/zendesk_api/resources.rb
- spec/live/user_spec.rb
Add [user related information operation](https://developer.zendesk.com/rest_api/docs/support/users#user-related-information) to the client API
Fixes #372
> Add user related operation

- lib/zendesk_api/resources.rb
Hello Team,
First, Thank you for maintaining Zendesk API Ruby client!
Please help me to introduce this fix!
Users have "update many" endpoint.
Ref. https://developer.zendesk.com/rest_api/docs/support/users#update-many-users
But it was removed by this commit; https://github.com/zendesk/zendesk_api_client_rb/commit/f34990dc9f4cbdb66d5cfec7ddf4c7ff05ab77c7
So this is a fix to add the endpoint.
As a background, I maintain the following tool to add some user attribution data to our Zendesk User Fields. Then, the latest version doesn't work because the tool uses update_many!
https://github.com/toru-takahashi/embulk-output-zendesk_users
> Add "update many" to users

- lib/zendesk_api/middleware/request/etag_cache.rb
- lib/zendesk_api/middleware/response/raise_error.rb
- spec/core/middleware/response/raise_error_spec.rb
- zendesk_api.gemspec
[Faraday has released a 1.0 version](https://github.com/lostisland/faraday/blob/master/CHANGELOG.md#v10) last month, but `zendesk_api` depends on the `0.x` series of Faraday versions by gemspec.  
Let's allow using the latest version of Faraday but avoid a major upgrade to `2.x` by maintaining a version constraint.
**Backward compatibility fixes (v. 0.9 - v 1.x compatible):**
* Fix references to the `Faraday::Error` module which was [removed in v `0.9.0` of Faraday](https://github.com/lostisland/faraday/commit/a6c6f1612c225335bf3bf94cf0b88e2e9a315671#diff-1b35e95f85a819bcd3c16d920ecdcffe).
* [Fix serialized environment]](https://github.com/lostisland/faraday/pull/847) for [Etag cache middleware](https://github.com/zendesk/zendesk_api_client_rb/blob/b5c53106bfb1e19715dcc1c167a65b7eb1021c9f/ …
> Allow using Faraday 1.x release in gemspec

- zendesk_api.gemspec
This change seems safe - there are very few backwards-incompatible changes in Hashie v4. The changelog can be found [here](https://github.com/hashie/hashie/blob/master/CHANGELOG.md).
> Allow using hashie 4.x

- lib/zendesk_api/resources.rb
Fix #330
This pull request will add a way to merge a user to another one. It corresponds to "Merge End Users API" https://developer.zendesk.com/rest_api/docs/support/users#merge-end-users
```ruby
client = ZendeskAPI::Client.new { |config| ... }
user1 = ZendeskAPI::User.create! client, email: 'aaa@example.com', name: 'aaa'
user2 = ZendeskAPI::User.create! client, email: 'bbb@example.com', name: 'bbb'
user1.merge! user: { id: user2.id }
```
Note that this change conceals current `ZendeskAPI::User#merge` method.
Currently `ZendeskAPI::User` has `merge` method via `method_missing`.
https://developer.zendesk.com/rest_api/docs/support/users#merge-end-users
This pull request adds an actual `merge` method to the class, so it conceals the delegated `merge` method. 
But I think it will be not a …
> Add support to merge user API

- zendesk_api.gemspec
According to terms of the license, to redistribute the package one must also provide a copy of the license.
https://github.com/zendesk/zendesk_api_client_rb/blob/fd431b4b6b5e37906d5e235481e1cfe984830f92/LICENSE#L94-L95
Let's make this easy by including the license in the gem package.
> Include license in the gem package

- .github/workflows/main.yml
- Gemfile
- README.md
Use `json` library > 2.3 for ruby 1.9 platforms and update README badge to use the new GitHub actions workflow
> Upgrade JSON library and change README badge to use GitHub actions

- README.md
Not being able to directly add/modify ticket attributes then saving has caused some frustration. This is also a bit counter-intuitive when combined with Rails syntax where `.update` is a direct method call to save modified values without needing to `.save`. See https://support.zendesk.com/hc/en-us/articles/226316187-Adding-a-comment-to-a-ticket-via-the-API for more examples of confusion.
> Add update method example to the README

- Gemfile
- lib/zendesk_api/middleware/request/upload.rb
- zendesk_api.gemspec
The mime-types gem is used to determine the MIME type of the uploaded file via the filename.
The [mini_mime](https://github.com/discourse/mini_mime) library is an alternative which has a lower memory footprint. [This pull request on the mail library](https://github.com/mikel/mail/pull/1059) has some discussion on the topic.
> Replace mime-types dependency with mini_mime

- spec/live/suspended_ticket_spec.rb
We have lost the ability to dynamically create suspended tickets via the API. Thus, we can't create the necessary suspended tickets to test the Index endpoint, and the delete suspended ticket endpoint
> Disable suspended tickets tests

- .github/workflows/main.yml
Updated the tested list of Ruby versions used for GitHub Actions.
Added:
- 2.7: Released 2019-12-25
- 3.0: Released 2020-12-25
Removed:
- 2.3: EOL 2019-03-31
- 2.4: EOL 2020-03-31
https://www.ruby-lang.org/en/downloads/branches/
> Update tested Ruby versions

- lib/zendesk_api/error.rb
- spec/core/middleware/response/raise_error_spec.rb
* The error message for `ZendeskAPI::Error::RecordInvalid` does not contain sufficient information at times. Taking the following response body as an example:
```ruby
{
"error"=>"ZuoraClient::SubscribeCommandFailure",
"description"=>"An internal error occurred. Please try again", 
"message"=>"[ TRANSACTION_FAILED: Merchant bank information is incorrect. Check gateway provider settings.999 - Internal Error ]"
}
```
* Original output -> `ZendeskAPI::Error::RecordInvalid: ZendeskAPI::Error::RecordInvalid: An internal error occurred. Please try again`
* New output -> `ZendeskAPI::Error::RecordInvalid: ZendeskAPI::Error::RecordInvalid: An internal error occurred. Please try again - [ TRANSACTION_FAILED: Merchant bank information is incorrect. Check gateway provider settings.999 - Internal …
> [ZTF-2569] Add more info to ZendeskAPI::Error::RecordInvalid

- lib/zendesk_api/client.rb
- lib/zendesk_api/configuration.rb
- lib/zendesk_api/middleware/request/retry.rb
- spec/core/middleware/request/retry_spec.rb
@haljor 
@grahamcruse 
@alanzoppa 
@zenspider 
@snbloch 
Improves retries when layer 3 errors occur and adds 504 network gateway timeouts.
This should improve resiliency a bit when executing the tests.
Adds test and I tested with consumer libs (doesn't crash/hurt/maim consumers)
> ORCD-1012 Network errors are retried if retry = true

- zendesk_api.gemspec
Hashie 5.0.0 is out now, and the restrictions in the gemspec prevent
this gem from working with applications that are using it.
Discourse would like to upgrade to the latest version of this gem
and we cannot support our zendesk plugin without this patch.
> Support installations with hashie 5.0.0

- lib/zendesk_api/client.rb
- spec/core/client_spec.rb
1. Disallow multiline url where one of the lines starts with `https`
2. Check for `https://` instead of `https`
3. Allow objects responding to `#to_str` like `Addressable::URI`
> Refine `https` check for URL

- lib/zendesk_api/collection.rb
- lib/zendesk_api/resources.rb
- spec/core/collection_spec.rb
- spec/core/search_export_spec.rb
The Zendesk Support, Talk, and Help Center APIs have several endpoints that return lists of items, such as tickets, users, or articles.
For performance reasons, the APIs do not return large record sets all at once. Instead, they break up the results into smaller subsets and return them in pages. The number of items per page varies by the endpoint. For example, the tickets and users' endpoints return 100 items per page while the articles endpoint returns 30 items per page.
Zendesk has two methods of paginating through resources:
Offset pagination (previously referred to as just pagination). This method is supported by all resources. See Paginating through lists using offset pagination for detailed instructions.
Cursor pagination. This method is supported by most resources, such as tickets …
> Adding Cursor Pagination to the gem by the Search Export Results

- Gemfile
Basically, we don't lock our libraries, and there have been some breaking changes these days, so, for now, I'm locking the gems directly in Gemfile, but I have created a ticket to use a lock file.
Details:
https://zendesk.atlassian.net/browse/RED-911
https://zendesk.atlassian.net/browse/RED-913
> Gemfile: Lock rspec version, newer breaks CI

- lib/zendesk_api/resource.rb
- lib/zendesk_api/resources.rb
- spec/live/ticket_spec.rb
https://github.com/zendesk/zendesk_api_client_rb/issues/321
Ticket "Comments" are not regular attributes to be sent only when they change, but they should be sent un-altered all the time.
> Fix issue #321: Ticket Comments should be sent unchanged

- lib/zendesk_api/collection.rb
- lib/zendesk_api/resources.rb
- spec/live/article_spec.rb
- spec/live/topic_subscription_spec.rb
Allows retrieving article votes:
```ruby
article = client.articles.find(id: 123)
article.votes.fetch!
```
See: 
* https://github.com/zendesk/zendesk_api_client_rb/issues/294
* https://developer.zendesk.com/api-reference/help_center/help-center-api/votes/
> Fix #294 Get article votes

- lib/zendesk_api/client.rb
- spec/core/client_spec.rb
Fixes the deprecation errors:
```
WARNING: `Faraday::Connection#authorization` is deprecated; it will be removed in version 2.0.
While initializing your connection, use `#request(:authorization, ...)` instead.
```
I couldn't directly use the client in the test since faraday only edits the headers somewhere using the middleware. So I had to make a request and check the request_header there.
> Fix faraday deprecation errors for `authorization`

- lib/zendesk_api/resources.rb
- spec/live/article_spec.rb
cc: @zendesk/i18n 
Per the [API docs](https://developer.zendesk.com/api-reference/help_center/help-center-api/article_labels/), we are able to list / add / remove labels from articles. This adds support for those endpoints to this client.
📝 This can currently be done using `article#update(label_names:)`, which will _overwrite_ the labels on a given article with whatever labels are passed to the update.
> Add `Article::Label` resource
