README.md

:koala: 
This PR updates README about installation creation
@steved555 
/cc @zendesk/quokka

Update installation creation example

---

lib/zendesk_api/resources.rb

:koala:
Add plan resource to apps.
API implemented in https://github.com/zendesk/zendesk_app_market/pull/1247.
/cc @zendesk/quokka @steved 
- Jira link: https://zendesk.atlassian.net/browse/APPS-2352
- None

[APPS-2352] Add plan resource to apps

---

lib/zendesk_api/middleware/response/raise_error.rb
spec/core/middleware/response/raise_error_spec.rb

@vkmita do you mind confirming I'm not crazy and we don't use any of those response codes?

Consider 3XX and 1XX responses invalid (except for 304)

---

lib/zendesk_api/actions.rb
lib/zendesk_api/resource.rb
lib/zendesk_api/resources.rb
spec/core/bulk_actions_spec.rb
spec/fixtures/test_resources.rb

Support for bulk actions.
/cc @zendesk/octo

Bulk actions!

---

lib/zendesk_api/resources.rb
spec/live/organization_membership_spec.rb

This PR adds the Organization Membership resource, fixing #239.

Adds Organization Membership resource

---

lib/zendesk_api/actions.rb
lib/zendesk_api/collection.rb
lib/zendesk_api/resources.rb
spec/core/bulk_actions_spec.rb
spec/core/collection_spec.rb
spec/fixtures/test_resources.rb

This introduces the `update_many!` action via an optional `UpdateMany` module.
So far this is mixed into `Ticket`
/cc @zendesk/octo @steved

Implement update_many!

---

lib/zendesk_api/middleware/response/parse_json.rb

:koala:
/cc @zendesk/quokka @steved

remove extra line

---

lib/zendesk_api/resources.rb

https://developer.zendesk.com/rest_api/docs/core/group_memberships#set-m
embership-as-default

Add agent Set Group Membership as Default

---

.rubocop.yml
.rubocop_todo.yml
Rakefile
lib/zendesk_api/actions.rb
lib/zendesk_api/client.rb
lib/zendesk_api/collection.rb
lib/zendesk_api/resource.rb
lib/zendesk_api/resources.rb
lib/zendesk_api/track_changes.rb
spec/core/association_spec.rb
spec/core/middleware/request/encode_json_spec.rb
spec/core/resource_spec.rb
spec/core/spec_helper.rb
spec/fixtures/zendesk.rb
spec/live/setting_spec.rb
util/resource_handler.rb

More Rubocop

---

Gemfile
lib/zendesk_api/resources.rb
spec/live/organization_subscription_spec.rb
zendesk_api.gemspec

/cc @grosser 
- Added support for https://developer.zendesk.com/rest_api/docs/core/organization_subscriptions resource
- Moved dev dependencies to Gemfile
- Fixed travis build for ruby 1.9.3
* [low] Only new code may not work: `org.subscriptions` & `user.organization_subscriptions`

added OrganizationSubscription resource

---

lib/zendesk_api/error.rb
spec/core/error_spec.rb

make error also work without an response

---

CHANGELOG.md

Update CHANGELOG.md through v1.17.0

---

lib/zendesk_api/middleware/request/raise_rate_limited.rb
spec/core/middleware/request/raise_rate_limited_spec.rb

Travis builds have been broken for a while due Rubocop errors. This PR should fix all those errors so we can go back to 💚

Fix rubocop errors

---

README.md

Some minor cleanup to the README

---

CHANGELOG.md

Update changelog up to 1.20.0

---

lib/zendesk_api/resources.rb

Support following api requests for organization resource.
+ create_many
+ https://developer.zendesk.com/rest_api/docs/support/organizations#create-many-organizations
+ create_or_update
+ https://developer.zendesk.com/rest_api/docs/support/organizations#create-or-update-organization
+ destroy_many
+ https://developer.zendesk.com/rest_api/docs/support/organizations#bulk-delete-organizations

Add support for create_many, create_or_update, destroy_many for organization resource

---

spec/live/organization_spec.rb

This PR adds integration test for the bulk actions that have been added to the organization resource here: https://github.com/zendesk/zendesk_api_client_rb/pull/406

Add integration tests for bulk organization actions

---

zendesk_api.gemspec

fix hard dependency on Faraday ~> 0.9.x

---

spec/live/user_spec.rb

Adding some live tests for some user bulk operations that were missing

Add integration tests for some bulk user actions

---

spec/live/user_spec.rb

Add integration tests for users#merge operation added in https://github.com/zendesk/zendesk_api_client_rb/pull/423

Add user#merge integration tests

---

lib/zendesk_api/resources.rb
spec/fixtures/zendesk.rb
spec/live/article_spec.rb
spec/live/section_spec.rb

Adds resources for Help Center / Explore's `Articles` and `Sections`.

Add resources for Help Center > Articles and Sections

---

lib/zendesk_api/resources.rb
spec/live/trigger_category_spec.rb
spec/live/trigger_spec.rb

Hi there, adding the resource for the new Trigger Categories api.
Thanks!

Add TriggerCategory resource

---

lib/zendesk_api/resources.rb
spec/live/organization_spec.rb

Add support for https://developer.zendesk.com/rest_api/docs/support/organizations#show-organizations-related-information

Add organization related information

---

lib/zendesk_api/resources.rb

https://developer.zendesk.com/rest_api/docs/support/support_addresses

adding RecipientAddress resource

---

README.md
lib/zendesk_api/client.rb
lib/zendesk_api/configuration.rb
spec/core/client_spec.rb
spec/core/configuration_spec.rb

We want an option to be able to turn off the resource cache for use in tests

Add option to disable resource cache

---

lib/zendesk_api/resources.rb
spec/live/organization_membership_spec.rb
spec/live/organization_spec.rb

Didn't tested because I don't have proper zendesk credentials ._.

Add `OrganizationMembership.create_or_update{,!}`

---

.github/workflows/main.yml
README.md
lib/zendesk_api/collection.rb
spec/core/collection_spec.rb
spec/core/search_export_spec.rb

💣 My first PR in this project.
* Currently, master CI is failing. This solves the problem
* Tiny code refactor for simplicity
* Improved README with local run instructions
* Run tests on Ruby 3.1 too, not on 2.5 (eol)
Maybe needs a bump version?

Fix Linting and CI test Ruby 3.1

---

CHANGELOG.md
README.md
lib/zendesk_api/collection.rb
lib/zendesk_api/resources.rb
lib/zendesk_api/version.rb

I will push to artifactory once merged.

Bump v1.35.0

---

CHANGELOG.md
lib/zendesk_api/resource.rb
lib/zendesk_api/resources.rb
spec/live/schedule_spec.rb
spec/live/webhook_spec.rb

See #281 .
Adds support for `Schedule` policy.

Business hours schedules

---

README.md

Please also review the linked project, I've done it in one commit and it's a few small files.

README: Doc REPL project

---

lib/zendesk_api/resources.rb
spec/live/custom_status_spec.rb

Add the resource CustomStatus to the gem
```rb
client.custom_statuses.create!(:status_category => 'open', :agent_label => 'In processing')
client.custom_statuses.to_a
client.custom_statuses.find!(:id => 1)
client.custom_statuses.update!(:id => 1,  :agent_label => 'Urgent')
client.custom_statuses.destroy!(:id => 1)
```

Add resource CustomStatus

---

CHANGELOG.md
lib/zendesk_api/version.rb

- [Changes since last release](https://github.com/zendesk/zendesk_api_client_rb/compare/v1.38.0.rc1...master)
cc: @zendesk/i18n

v1.38.0.rc2 release prep
